In [1]:
import numpy as np

# Basic indicing and methods 

In [102]:
a = np.array([1, 2, 3], dtype = 'int16')
print(a)

[1 2 3]


In [103]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [104]:
# get dimension
a.ndim

1

In [105]:
# Get shape
b.shape

(2, 3)

In [106]:
#Get Type

a.dtype

dtype('int16')

In [107]:
# Get size

a.itemsize

2

In [108]:
# Get total size
# a.size * a.itemsize this code can be replaced by the below function
a.nbytes

6

# Accessing/changing Specific elements, rows, columns, etc

In [131]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [110]:
# Get a specific element [r, c]
a[1, 5]

13

In [111]:
# Get a specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [112]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [113]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [114]:
# Changing values of elements, row, column

a[1, 5] = 20 # single element
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [115]:
# 3-d example

b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [116]:
b[1, 1, 1]

8

In [117]:
# replace

b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different types of arrays: 

In [118]:
# All zeros matrix

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [119]:
# All ones matrix

np.ones((2, 3), dtype = "int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [120]:
# for other numbers

np.full((2, 3), 99, dtype="float32")

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [121]:
# for other numbers(full-like)

np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [129]:
#Random decimal numbers

np.random.rand(4, 2)

array([[0.9653838 , 0.84333194],
       [0.57745615, 0.10333496],
       [0.02802016, 0.33796583],
       [0.23247784, 0.68175385]])

In [132]:
np.random.random_sample(a.shape)

array([[0.34435553, 0.64262826, 0.32616314, 0.60150969, 0.53119149,
        0.47537479, 0.37198056],
       [0.52058335, 0.94152389, 0.35281484, 0.34361114, 0.62563482,
        0.16222085, 0.71013919]])

In [168]:
# Random integer values

np.random.randint(-4, 8, size=(3, 3))

array([[-3,  6,  5],
       [ 2,  7,  7],
       [ 3,  4,  3]])

In [174]:
# Identity matrix

np.identity(2, dtype="int32")

array([[1, 0],
       [0, 1]])

In [182]:
# repeat an array

arr = np.array([[1, 2, 3]])
r = np.repeat(arr, 3, axis = 0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [189]:
'''
Problem statement: Replicate the following matrix using the methods learnt

1 1 1 1 1 
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
'''

matrix = np.ones([5, 5], dtype = "int32")
matrix[1:4, 1:4] = 0
matrix[2, 2] = 9
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful while copying arrays!!!

In [194]:
a = np.array([1, 2, 3])
b = a # here b is not a copy of a but is just pointing the variable a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [197]:
a = np.array([1, 2, 3])
b = np.copy(a)
print(a)
print(b)
b[0] = 100
print(a)
b

[1 2 3]
[1 2 3]
[1 2 3]


array([100,   2,   3])

## Mathematics

In [27]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [28]:
a + 1

array([2, 3, 4, 5])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 3

array([ 3,  6,  9, 12])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a**2

array([ 1,  4,  9, 16])

In [34]:
b = np.array([2, 3, 4, 5])
a+b

array([3, 5, 7, 9])

In [33]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.exp(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


##### Linear algebra

In [40]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print(b)
np.matmul(a, b, )

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [43]:
# find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print(np.min(a, axis = 0))
print(np.max(a))
print(np.sum(a))


[[1 2 3]
 [4 5 6]]
[1 2 3]
6
21


#### Re-organizing arrays

In [57]:
# re-shape

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

after = np.reshape(before, (2, 2, 2)) #shape here is such that the number of elements in before and after shouldn't differ.Else its an error 
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
# Vertically stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontal stacking vectors

h1 = np.zeros((2, 4))
h2 = np.zeros((2, 3))
print(h1)
print(h2)
np.hstack([h1, h2])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Miscellaneous

In [21]:
filedata = np.genfromtxt(r'C:\Users\Shrikar\OneDrive\Documents\rough.txt', delimiter=',')
filedata = filedata.astype("int32")
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking and Advance indexing

In [17]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [18]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [20]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [22]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [23]:
# ~ - not
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])